# ใช้ PHP 8.2 พร้อม Apache เป็น base image
FROM php:8.2-apache

# เปิดใช้งาน mod_rewrite ของ Apache
RUN a2enmod rewrite

# ติดตั้งส่วนเสริมที่ Laravel ต้องใช้
RUN docker-php-ext-install pdo pdo_mysql

# คัดลอกโค้ด Laravel ไปยังโฟลเดอร์ /var/www/html ภายใน container
COPY . /var/www/html/

# ติดตั้ง Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# ตั้งค่า Permission ให้ Laravel
    RUN apt-get update && apt-get upgrade -y
RUN docker-php-ext-install pdo pdo_mysql


# ตั้งค่า permission ให้ Laravel สามารถทำงานได้อย่างถูกต้อง
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache


# ตั้งค่าตำแหน่งทำงานเป็น /var/www/html
WORKDIR /var/www/html

# ติดตั้ง dependencies ของ Laravel โดยไม่รวมแพ็กเกจที่ใช้สำหรับ development
RUN composer clear-cache \
    && composer install --no-dev --optimize-autoloader

# เปิดพอร์ต 80 เพื่อให้ container สามารถรับคำขอ HTTP ได้
EXPOSE 80

# รัน Apache เมื่อตัว container เริ่มทำงาน
CMD ["apache2-foreground"]

